services:
  web:
    build: .
    restart: unless-stopped
    ports:
      - "3042:3042"  # فتح البورت للعالم الخارجي (للتجربة فقط)
    environment:
      - NODE_ENV=production
    env_file:
      - .env
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
